### ISSUE TITLE
复现代码时遇到的一些问题，希望作者不吝赐教

### ISSUE THREAD

**Issue by Fino2020** [panshengyi/MemVul#1]
在使用allennlp运行样例代码`allennlp train MemVul/config_memory.json -s MemVul/out_memvul/ --include-package ``MemVul`时，遇到了如下图所示的问题，我的几个重要库版本为 `allennlp==2.4.0` ， `torch==1.8.1+cu111`， `CUDA：11.1`(由于11.2的cuda，我暂时没找到对应的torch版本，我暂时直接使用的11.1)
![image](https://github.com/panshengyi/MemVul/assets/66312471/8ec7dfae-257b-44e6-83c1-a3e9fee4a5b9)
看报错好像是allennlp的问题，请问有解决办法吗

**Comment by panshengyi** [comment]
你好，从报错看应该不是实验代码本身造成的，更像是环境的问题。我也没有遇到过这个问题，所以无法提供准确的解决方案，只简单说一下我的猜测：
1. 应该和torch，CUDA无关，或许可以检查一下python版本，实验的python版本为3.8.5
2. 这里import_module_and_submodules()应该是在导入MemVul文件夹下的所有submodules（register reader, model等），或许可以debug一下path这个object，path[0]导致了该报错，获取path的逻辑见import_module_and_submodules()这个函数，应该不难理解

希望能帮到你

**Comment by panshengyi** [comment]
你好，从报错看应该不是实验代码本身造成的，更像是环境的问题。我也没有遇到过这个问题，所以无法提供准确的解决方案，只简单说一下我的猜测：
1. 应该和torch，CUDA无关，或许可以检查一下python版本，实验的python版本为3.8.5
2. 这里import_module_and_submodules()应该是在导入MemVul文件夹下的所有submodules（register reader, model等），或许可以debug一下path这个object，应该是path[0]导致了该报错，获取path的逻辑可见import_module_and_submodules()这个函数

希望有所帮助
