### ISSUE TITLE
predict_memory and predict_single archive files

### ISSUE THREAD

**Issue by Jesse-Na** [panshengyi/MemVul#2]
Hi, I am wondering if it is possible to provide the archive files that you used when running the experiments to evaluate MemVul in your paper. These files are necessary to run predict_memory.py and predict_single.py, and re-building them would be extremely time consuming, so it would be great if you could upload them somewhere. Thank you!

**Comment by panshengyi** [comment]
Hi Jesse, sorry for the late reply. The archive files have been shared through email. Please check your mailbox.
